### ISSUE TITLE
Installer wizard can't see my Python installation

### ISSUE THREAD

**Issue by slott56** [axper/python3-pycrypto-windows-installer#2]
And freezes there. None of the fields are filled in to pick an installation. 

c:\python34 is on the path.

Is there a way to tweak the installer so that the "not found in the registry" allows some input?

**Comment by axper** [comment]
Seems like this is a problem with either your setup or distutils. Can you please try installing some other module which has an installer built with distutils, and see whether this problem still appears?

**Comment by slott56** [comment]
"some other module"? Any suggestions as to which would provide a good test case?

**Comment by axper** [comment]
Try this: http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/

**Comment by slott56** [comment]
Same response. The Python 3.4 is not being detected.

It is present:

```
C:\Users\pha212>c:\python34\python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

[It's not on my path because I'm using Python3.3 for the time being.]

The installer isn't seeing it. 

![image](https://cloud.githubusercontent.com/assets/1441257/7597563/5dcc6984-f8c2-11e4-8be2-8de4d003505b.png)

**Comment by axper** [comment]
Then this is a problem either with distutils or with your setup. I suggest either asking for help from distutil guys and/or completely re-installing all your python installs (starting from fresh windows install will be even better).
