### ISSUE TITLE
How to install into VirtualEnv so that it is visible to use in them ?

### ISSUE THREAD

**Issue by Smurf-IV** [axper/python3-pycrypto-windows-installer#4]
How to install into **VirtualEnv** so that it is visible to use in them ?

**Comment by Smurf-IV** [comment]
Sorted, might help if this is placed ont the readme page:

```
# Run and then copy the following (to the equivalent location) into your virtual env
# C:\Python34\Lib\site-packages\pycrypto-2.6.1-py3.4.egg-info

```

**Comment by LotosikRa** [comment]
Maybe you must run `.exe` from comand line with activated venv? (I didn't try)

**Comment by Smurf-IV** [comment]
See comment from  28 Jul 2016
